#!/usr/bin/env bash
# process and pid file
echo "$$" > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid' 15
trap 'echo "Y U no love me?!"' 2
trap 'rm /var/run/myscript.pid' 3
while true; do
    echo "To infinity and beyond"
    sleep 2
done
