#!/usr/bin/env bash
#print 1 to 20
i=1
while((i < 21)); do
    if((i == 5)); then
        echo "bad luck from China"
        echo "$i"
    elif((i == 10)); then
        echo "bad luck from Japan"
        echo "$i"
    elif((i == 18)); then
        echo "bad luck from Italy"
	echo "$i"
    else
        echo "$i"
    fi
    ((i++))
done
